
import React, { createContext, useContext, useState, ReactNode } from 'react';
import { TenantConfig, TenantFeatures, TenantStatus } from '../types';

interface TenantContextType {
  tenant: TenantConfig | null; // The currently active tenant for the view
  setTenant: (tenant: TenantConfig) => void;
  tenants: TenantConfig[]; // Master list for Superuser
  createTenant: (config: Omit<TenantConfig, 'id' | 'createdAt' | 'status'>) => void;
  updateTenantFeatures: (id: string, features: TenantFeatures) => void;
  updateTenantStatus: (id: string, status: TenantStatus) => void;
  updateTenantDetails: (id: string, updates: Partial<TenantConfig>) => void;
  deleteTenant: (id: string) => void;
  brandColor: (opacity?: number) => string;
}

const TenantContext = createContext<TenantContextType | undefined>(undefined);

// Initial Data
const INITIAL_TENANTS: TenantConfig[] = [
  {
    id: 't-dev-001',
    name: 'InvoiceFlow Labs (BETA)',
    primaryColor: '#7c3aed', // violet-600
    secondaryColor: '#4c1d95', // violet-900
    accentColor: '#d946ef', // fuchsia-500
    features: { aiAudit: true, xeroIntegration: true, poMatching: true, spendingAnalysis: true, emailIngestion: true },
    status: 'BETA',
    createdAt: '2023-01-01',
    documentSettings: {
        headerText: 'InvoiceFlow Labs (BETA)',
        subHeaderText: 'Development Environment',
        footerText: 'Confidential - Internal Use Only | ABN 12 345 678 901',
        showLogo: true
    }
  },
  {
    id: 't-001',
    name: 'CareFirst Solutions',
    primaryColor: '#2563eb', // blue-600
    secondaryColor: '#1e40af', // blue-800
    accentColor: '#3b82f6', // blue-500
    features: { aiAudit: true, xeroIntegration: true, poMatching: true, spendingAnalysis: true, emailIngestion: true },
    status: 'ACTIVE',
    createdAt: '2023-01-15',
    documentSettings: {
        headerText: 'CareFirst Solutions',
        subHeaderText: 'Excellence in Care',
        footerText: 'CareFirst Solutions Pty Ltd | ABN 88 999 111 222 | Privacy Policy available at carefirst.com.au',
        showLogo: true
    }
  },
  {
    id: 't-002',
    name: 'GreenLeaf Support',
    primaryColor: '#059669', // emerald-600
    secondaryColor: '#065f46', // emerald-800
    accentColor: '#10b981', // emerald-500
    features: { aiAudit: true, xeroIntegration: false, poMatching: true, spendingAnalysis: false, emailIngestion: false },
    status: 'ACTIVE',
    createdAt: '2023-03-22',
    documentSettings: {
        headerText: 'GreenLeaf Support Services',
        subHeaderText: 'Supporting Your Independence',
        footerText: 'GreenLeaf Support | Registered NDIS Provider | 1300 000 000',
        showLogo: false
    }
  },
  {
    id: 't-003',
    name: 'Horizon Health',
    primaryColor: '#6366f1', // indigo-500
    secondaryColor: '#312e81', // indigo-900
    accentColor: '#818cf8', // indigo-400
    features: { aiAudit: false, xeroIntegration: true, poMatching: false, spendingAnalysis: false, emailIngestion: true },
    status: 'ACTIVE',
    createdAt: '2023-06-10',
    documentSettings: {
        headerText: 'Horizon Health',
        subHeaderText: '',
        footerText: 'Horizon Health Ltd. All rights reserved.',
        showLogo: true
    }
  }
];

export const TenantProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [tenant, setTenant] = useState<TenantConfig | null>(null);
  const [tenants, setTenants] = useState<TenantConfig[]>(INITIAL_TENANTS);

  const createTenant = (config: Omit<TenantConfig, 'id' | 'createdAt' | 'status'>) => {
    const newTenant: TenantConfig = {
      ...config,
      id: `t-${Date.now()}`,
      status: 'ACTIVE',
      createdAt: new Date().toISOString().split('T')[0],
      documentSettings: config.documentSettings || {
          headerText: config.name,
          subHeaderText: '',
          footerText: `${config.name} | Generated by InvoiceFlow`,
          showLogo: true
      }
    };
    setTenants(prev => [...prev, newTenant]);
  };

  const updateTenantFeatures = (id: string, features: TenantFeatures) => {
    setTenants(prev => prev.map(t => t.id === id ? { ...t, features } : t));
    // Also update active tenant if it matches
    if (tenant && tenant.id === id) {
        setTenant(prev => prev ? { ...prev, features } : null);
    }
  };

  const updateTenantStatus = (id: string, status: TenantStatus) => {
      setTenants(prev => prev.map(t => t.id === id ? { ...t, status } : t));
      if (tenant && tenant.id === id) {
          setTenant(prev => prev ? { ...prev, status } : null);
      }
  };

  const updateTenantDetails = (id: string, updates: Partial<TenantConfig>) => {
      setTenants(prev => prev.map(t => t.id === id ? { ...t, ...updates } : t));
      if (tenant && tenant.id === id) {
          setTenant(prev => prev ? { ...prev, ...updates } : null);
      }
  };

  const deleteTenant = (id: string) => {
      setTenants(prev => prev.filter(t => t.id !== id));
      if (tenant && tenant.id === id) {
          setTenant(null);
      }
  };

  // Helper to generate dynamic styles
  const brandColor = (opacity: number = 1) => {
    if (!tenant) return `rgba(37, 99, 235, ${opacity})`;
    return tenant.primaryColor;
  };

  return (
    <TenantContext.Provider value={{ tenant, setTenant, tenants, createTenant, updateTenantFeatures, updateTenantStatus, updateTenantDetails, deleteTenant, brandColor }}>
      {children}
    </TenantContext.Provider>
  );
};

export const useTenant = () => {
  const context = useContext(TenantContext);
  if (!context) {
    throw new Error('useTenant must be used within a TenantProvider');
  }
  return context;
};
