
import React, { useState, useEffect, useRef } from 'react';
import { useTenant } from '../contexts/TenantContext';
import { TenantConfig, TenantFeatures, TenantStatus, WeeklySystemAuditReport, DocumentSettings } from '../types';
import { Building2, Plus, Users, Settings, Activity, Shield, ToggleLeft, ToggleRight, Copy, Check, X, Palette, Lock, LogIn, Archive, PauseCircle, PlayCircle, Trash2, AlertTriangle, MoreVertical, Terminal, Database, Server, RefreshCw, TestTube, Zap, Bell, Globe, Clock, FileText, Image as ImageIcon, LayoutTemplate, Sparkles, Loader2, Scale, ScrollText } from 'lucide-react';
import { generateBrandingProfile, performWeeklySystemAudit } from '../services/geminiService';
import { MOCK_INVOICES } from '../constants'; // Using MOCK_INVOICES for the audit

const FEATURE_LABELS: Record<keyof TenantFeatures, string> = {
    aiAudit: "AI Fraud Audit",
    xeroIntegration: "Xero Sync",
    poMatching: "PO Matching",
    spendingAnalysis: "Budget AI",
    emailIngestion: "Email Ingestion"
};

// Initial Mock Users
const INITIAL_USERS: Record<string, any[]> = {
    't-001': [
        { id: 1, email: 'admin@carefirst.com', role: 'Administrator', status: 'Active', lastActive: '2 mins ago' },
        { id: 2, email: 'finance@carefirst.com', role: 'Officer', status: 'Active', lastActive: '2 days ago' }
    ],
    't-002': [
        { id: 3, email: 'manager@greenleaf.com', role: 'Administrator', status: 'Active', lastActive: '5 hours ago' }
    ]
};

const MOCK_AUDIT_LOGS = [
    { id: 101, action: "Tenant Created", actor: "superuser@system", target: "New Org Inc.", timestamp: "2023-10-28 14:30:00", status: "Success" },
    { id: 102, action: "Feature Toggle", actor: "superuser@system", target: "CareFirst (AI Audit)", timestamp: "2023-10-28 12:15:00", status: "Success" },
    { id: 103, action: "Failed Login", actor: "unknown@ip-221.33.22", target: "System", timestamp: "2023-10-28 09:00:00", status: "Failed" },
    { id: 104, action: "Global Config Update", actor: "superuser@system", target: "Maintenance Mode", timestamp: "2023-10-27 18:45:00", status: "Success" },
    { id: 105, action: "Tenant Suspended", actor: "superuser@system", target: "Old Test Org", timestamp: "2023-10-25 10:20:00", status: "Success" },
];

interface SuperuserDashboardProps {
    onImpersonate: (tenantId: string) => void;
    initialTab?: 'orgs' | 'system' | 'audit' | 'global_config';
}

const SuperuserDashboard: React.FC<SuperuserDashboardProps> = ({ onImpersonate, initialTab = 'orgs' }) => {
  const { tenants, createTenant, updateTenantFeatures, updateTenantStatus, updateTenantDetails, deleteTenant } = useTenant();
  
  // Tab State
  const [activeTab, setActiveTab] = useState<'orgs' | 'system' | 'audit' | 'global_config' | 'chief_audit'>(initialTab);

  useEffect(() => {
      setActiveTab(initialTab);
  }, [initialTab]);

  // Create Modal State
  const [isCreateModalOpen, setIsCreateModalOpen] = useState(false);
  const [newOrgName, setNewOrgName] = useState('');
  const [newOrgColor, setNewOrgColor] = useState('#2563eb');
  const [newOrgLogo, setNewOrgLogo] = useState('');
  const [newOrgWebsite, setNewOrgWebsite] = useState(''); // New input
  const [newOrgDocSettings, setNewOrgDocSettings] = useState<DocumentSettings>({
      headerText: '',
      subHeaderText: '',
      footerText: 'Confidential | Generated by InvoiceFlow',
      showLogo: true
  });
  const [isGeneratingCreate, setIsGeneratingCreate] = useState(false);

  // Edit Modal State
  const [editingTenant, setEditingTenant] = useState<TenantConfig | null>(null);
  const [editForm, setEditForm] = useState({ 
      name: '', 
      primaryColor: '', 
      logoUrl: '', 
      website: '',
      documentSettings: (tenant: TenantConfig) => ({
          headerText: tenant.name,
          subHeaderText: '',
          footerText: `${tenant.name} | Confidential`,
          showLogo: true
      })
  });
  const [isGeneratingEdit, setIsGeneratingEdit] = useState(false);

  // User Management State
  const [userModalOpen, setUserModalOpen] = useState<{isOpen: boolean, tenantId: string, tenantName: string}>({ isOpen: false, tenantId: '', tenantName: '' });
  const [adminEmail, setAdminEmail] = useState('');
  const [adminRole, setAdminRole] = useState('Administrator');
  const [inviteLink, setInviteLink] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  
  // Persistent Users Store (In-Memory for Session)
  const [usersByTenant, setUsersByTenant] = useState<Record<string, any[]>>(INITIAL_USERS);

  // Status Action State
  const [actionMenuOpen, setActionMenuOpen] = useState<string | null>(null);

  // Weekly Audit State
  const [isRunningWeeklyAudit, setIsRunningWeeklyAudit] = useState(false);
  const [weeklyReport, setWeeklyReport] = useState<WeeklySystemAuditReport | null>(null);

  // File Input Refs
  const createLogoRef = useRef<HTMLInputElement>(null);
  const editLogoRef = useRef<HTMLInputElement>(null);

  // Global Config State
  const [globalConfig, setGlobalConfig] = useState({
      maintenanceMode: false,
      systemBanner: '',
      allowNewRegistrations: true,
      defaultRegion: 'au-southeast-1'
  });

  // Helper to darken/lighten hex color
  const adjustColor = (color: string, amount: number) => {
      try {
        return '#' + color.replace(/^#/, '').replace(/../g, color => ('0'+Math.min(255, Math.max(0, parseInt(color, 16) + amount)).toString(16)).substr(-2));
      } catch (e) {
        return color;
      }
  }

  // --- AI GENERATION LOGIC ---
  const handleGenerateBranding = async (
      type: 'create' | 'edit', 
      website: string, 
      logoUrl: string
  ) => {
      if (!website && !logoUrl) {
          alert("Please enter a Website URL or Upload a Logo first.");
          return;
      }

      const setter = type === 'create' ? setIsGeneratingCreate : setIsGeneratingEdit;
      setter(true);

      try {
          const logoBase64 = logoUrl.startsWith('data:image') ? logoUrl.split(',')[1] : null;
          const palette = await generateBrandingProfile(website, logoBase64);

          if (type === 'create') {
              setNewOrgColor(palette.primaryColor);
              // Auto-fill header
              if (!newOrgDocSettings.headerText) setNewOrgDocSettings(p => ({ ...p, headerText: newOrgName }));
          } else {
              setEditForm(prev => ({ ...prev, primaryColor: palette.primaryColor }));
          }
      } catch (e) {
          alert("Branding generation failed.");
      } finally {
          setter(false);
      }
  };

  const handleRunWeeklyAudit = async () => {
      setIsRunningWeeklyAudit(true);
      try {
          const report = await performWeeklySystemAudit(MOCK_INVOICES);
          setWeeklyReport(report);
      } catch (e) {
          console.error("Weekly audit failed", e);
          alert("Failed to run Weekly System Audit.");
      } finally {
          setIsRunningWeeklyAudit(false);
      }
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>, type: 'create' | 'edit') => {
      if (e.target.files && e.target.files[0]) {
          const file = e.target.files[0];
          const reader = new FileReader();
          reader.onload = (ev) => {
              const result = ev.target?.result as string;
              if (type === 'create') {
                  setNewOrgLogo(result);
              } else {
                  setEditForm(prev => ({ ...prev, logoUrl: result }));
              }
          };
          reader.readAsDataURL(file);
      }
  };

  const handleCreateTenant = (e: React.FormEvent) => {
    e.preventDefault();
    createTenant({
        name: newOrgName,
        primaryColor: newOrgColor,
        secondaryColor: adjustColor(newOrgColor, -40),
        accentColor: adjustColor(newOrgColor, 20),
        logoUrl: newOrgLogo || undefined,
        documentSettings: {
            ...newOrgDocSettings,
            headerText: newOrgDocSettings.headerText || newOrgName // Fallback to name if empty
        },
        features: {
            aiAudit: true,
            xeroIntegration: false,
            poMatching: true,
            spendingAnalysis: false,
            emailIngestion: true
        }
    });
    setIsCreateModalOpen(false);
    resetCreateForm();
  };

  const handleEditOpen = (tenant: TenantConfig) => {
      setEditingTenant(tenant);
      setEditForm({
          name: tenant.name,
          primaryColor: tenant.primaryColor,
          logoUrl: tenant.logoUrl || '',
          website: '',
          documentSettings: tenant.documentSettings || {
              headerText: tenant.name,
              subHeaderText: '',
              footerText: `${tenant.name} | Confidential`,
              showLogo: true
          }
      });
      setActionMenuOpen(null);
  };

  const handleUpdateTenant = (e: React.FormEvent) => {
      e.preventDefault();
      if (!editingTenant) return;

      updateTenantDetails(editingTenant.id, {
          name: editForm.name,
          primaryColor: editForm.primaryColor,
          secondaryColor: adjustColor(editForm.primaryColor, -40),
          accentColor: adjustColor(editForm.primaryColor, 20),
          logoUrl: editForm.logoUrl || undefined,
          documentSettings: editForm.documentSettings as any
      });
      setEditingTenant(null);
  };

  const resetCreateForm = () => {
      setNewOrgName('');
      setNewOrgColor('#2563eb');
      setNewOrgLogo('');
      setNewOrgWebsite('');
      setNewOrgDocSettings({
        headerText: '',
        subHeaderText: '',
        footerText: 'Confidential | Generated by InvoiceFlow',
        showLogo: true
      });
  };

  const handleToggleFeature = (tenant: TenantConfig, feature: keyof TenantFeatures) => {
      const updatedFeatures = {
          ...tenant.features,
          [feature]: !tenant.features[feature]
      };
      updateTenantFeatures(tenant.id, updatedFeatures);
  };

  const handleStatusChange = (tenantId: string, status: TenantStatus) => {
      updateTenantStatus(tenantId, status);
      setActionMenuOpen(null);
  };

  const handleDelete = (tenantId: string, tenantName: string) => {
      if (confirm(`Are you absolutely sure you want to PERMANENTLY DELETE "${tenantName}"?\n\nThis action cannot be undone.`)) {
          deleteTenant(tenantId);
          setActionMenuOpen(null);
      }
  };

  const handleRevokeUser = (userId: number) => {
      if(confirm("Revoke access for this user?")) {
          const tid = userModalOpen.tenantId;
          setUsersByTenant(prev => ({
              ...prev,
              [tid]: (prev[tid] || []).filter(u => u.id !== userId)
          }));
      }
  };

  const handleResetPassword = (email: string) => {
      alert(`Password reset link sent to ${email}`);
  };

  const generateInvite = () => {
      if (!adminEmail) return;
      const tid = userModalOpen.tenantId;
      const token = btoa(`${tid}-${adminEmail}-${Date.now()}`);
      const link = `${window.location.origin}/join?token=${token}`;
      setInviteLink(link);
      
      const newUser = { 
          id: Date.now(), 
          email: adminEmail, 
          role: adminRole, 
          status: 'Pending', 
          lastActive: '-' 
      };

      setUsersByTenant(prev => ({
          ...prev,
          [tid]: [...(prev[tid] || []), newUser]
      }));
  };

  const copyToClipboard = () => {
      if (inviteLink) {
          navigator.clipboard.writeText(inviteLink);
          setCopied(true);
          setTimeout(() => setCopied(false), 2000);
      }
  };

  const getStatusColor = (status: TenantStatus) => {
      switch(status) {
          case 'ACTIVE': return 'bg-emerald-100 text-emerald-700 border-emerald-200';
          case 'SUSPENDED': return 'bg-amber-100 text-amber-700 border-amber-200';
          case 'ARCHIVED': return 'bg-slate-100 text-slate-500 border-slate-200';
          case 'BETA': return 'bg-fuchsia-100 text-fuchsia-700 border-fuchsia-200';
          default: return 'bg-slate-100 text-slate-700';
      }
  };

  const betaTenant = tenants.find(t => t.status === 'BETA');
  const prodTenants = tenants.filter(t => t.status !== 'BETA');

  // Preview Component for White Labeling
  const BrandingPreview = ({ name, color, logoUrl }: { name: string, color: string, logoUrl: string }) => (
      <div className="mt-4 border border-slate-200 rounded-xl overflow-hidden">
          <div className="bg-slate-50 px-4 py-2 border-b border-slate-200 text-xs font-bold text-slate-500 uppercase">
              Theme Preview
          </div>
          <div className="flex h-32">
              {/* Mock Sidebar */}
              <div 
                  className="w-1/3 p-4 flex flex-col justify-between"
                  style={{ background: `linear-gradient(180deg, ${adjustColor(color, -40)} 0%, #020617 100%)` }}
              >
                  <div className="flex items-center gap-2">
                      {logoUrl ? (
                          <img src={logoUrl} alt="Logo" className="w-6 h-6 object-contain" />
                      ) : (
                          <div className="w-6 h-6 bg-white/20 rounded flex items-center justify-center text-white text-[10px] font-bold">
                              {name ? name.substring(0, 2).toUpperCase() : 'OR'}
                          </div>
                      )}
                      <span className="text-white text-xs font-bold truncate">{name || 'Org Name'}</span>
                  </div>
                  <div className="space-y-2 opacity-50">
                      <div className="h-2 w-3/4 bg-white/20 rounded"></div>
                      <div className="h-2 w-1/2 bg-white/20 rounded"></div>
                  </div>
              </div>
              {/* Mock Content */}
              <div className="flex-1 bg-slate-50 p-4">
                  <div className="h-8 w-1/3 bg-white rounded shadow-sm mb-4 border border-slate-200"></div>
                  <div className="h-20 w-full bg-white rounded shadow-sm border border-slate-200"></div>
              </div>
          </div>
      </div>
  );

  const currentTenantUsers = userModalOpen.isOpen ? (usersByTenant[userModalOpen.tenantId] || []) : [];

  return (
    <div className="p-8 max-w-7xl mx-auto animate-fade-in pb-20">
      {/* Header */}
      <div className="flex justify-between items-end mb-8">
        <div>
           <div className="flex items-center gap-2 mb-1">
               <span className="bg-slate-900 text-white text-xs font-bold px-2 py-0.5 rounded uppercase tracking-wider">Superuser</span>
               <span className="text-slate-400 text-xs">System Administration</span>
           </div>
           <h2 className="text-3xl font-bold text-slate-800">Global Organisation Management</h2>
        </div>
        {activeTab === 'orgs' && (
            <button 
            onClick={() => setIsCreateModalOpen(true)}
            className="flex items-center gap-2 bg-indigo-600 hover:bg-indigo-700 text-white px-5 py-2.5 rounded-lg font-semibold shadow-lg shadow-indigo-200 transition-all active:scale-95"
            >
                <Plus size={20} /> Create Organisation
            </button>
        )}
      </div>

      {/* Tabs */}
      <div className="flex border-b border-slate-200 mb-8 overflow-x-auto">
          {[
              { id: 'orgs', label: `Organisations (${tenants.length})`, icon: Building2 },
              { id: 'chief_audit', label: 'Chief Auditor', icon: Scale },
              { id: 'audit', label: 'Audit Logs', icon: FileText },
              { id: 'global_config', label: 'Global Settings', icon: Settings },
              { id: 'system', label: 'System Health', icon: Activity },
          ].map(tab => {
              const Icon = tab.icon;
              return (
                <button 
                    key={tab.id}
                    onClick={() => setActiveTab(tab.id as any)}
                    className={`px-6 py-3 font-medium text-sm transition-colors border-b-2 flex items-center gap-2 whitespace-nowrap ${activeTab === tab.id ? 'border-indigo-600 text-indigo-700' : 'border-transparent text-slate-500 hover:text-slate-700'}`}
                >
                    <Icon size={16} />
                    {tab.label}
                </button>
              );
          })}
      </div>

      {activeTab === 'orgs' && (
          <div className="space-y-8 animate-in fade-in slide-in-from-bottom-2 duration-300">
              {/* Beta Lab Section */}
              {betaTenant && (
                  <div className="bg-slate-900 rounded-xl border border-slate-800 p-6 relative overflow-hidden group">
                      <div className="absolute top-0 right-0 w-64 h-64 bg-fuchsia-600/20 blur-[80px] rounded-full pointer-events-none"></div>
                      <div className="relative z-10 flex flex-col md:flex-row items-center justify-between gap-6">
                          <div className="flex items-center gap-5">
                              <div className="w-16 h-16 rounded-xl bg-gradient-to-br from-fuchsia-600 to-purple-800 flex items-center justify-center text-white shadow-lg shadow-purple-900/50">
                                  <TestTube size={32} />
                              </div>
                              <div>
                                  <div className="flex items-center gap-3">
                                      <h3 className="text-xl font-bold text-white">{betaTenant.name}</h3>
                                      <span className="px-2 py-0.5 rounded-full bg-fuchsia-500/20 text-fuchsia-300 text-xs font-bold border border-fuchsia-500/30 uppercase tracking-wide">
                                          Development Sandbox
                                      </span>
                                  </div>
                                  <p className="text-slate-400 text-sm mt-1 max-w-lg">
                                      Isolated environment for testing new features, validating Gemini 3 Pro audits, and running beta simulations without affecting production data.
                                  </p>
                              </div>
                          </div>
                          <button 
                              onClick={() => onImpersonate(betaTenant.id)}
                              className="px-6 py-3 bg-fuchsia-600 hover:bg-fuchsia-500 text-white rounded-xl font-bold shadow-lg shadow-fuchsia-900/40 transition-all transform hover:scale-105 flex items-center gap-2"
                          >
                              <Zap size={18} fill="currentColor" /> Enter Lab Environment
                          </button>
                      </div>
                  </div>
              )}

              {/* Production Tenants Grid */}
              <div className="grid grid-cols-1 gap-6">
                  <h4 className="text-sm font-bold text-slate-500 uppercase tracking-wider mb-2">Production Tenants</h4>
                  {prodTenants.map(tenant => (
                      <div key={tenant.id} className={`bg-white rounded-xl border shadow-sm hover:shadow-md transition-shadow ${tenant.status === 'ARCHIVED' ? 'border-slate-100 opacity-75 grayscale-[0.8]' : 'border-slate-200'}`}>
                          <div className="p-6 flex flex-col xl:flex-row gap-6">
                              
                              {/* Org Info */}
                              <div className="flex-1">
                                  <div className="flex items-center justify-between mb-3">
                                      <div className="flex items-center gap-4">
                                        <div className="w-12 h-12 rounded-lg flex items-center justify-center text-white font-bold text-xl shadow-inner relative overflow-hidden" style={{ backgroundColor: tenant.primaryColor }}>
                                            {tenant.logoUrl ? (
                                                <img src={tenant.logoUrl} alt="logo" className="w-full h-full object-cover opacity-90" />
                                            ) : (
                                                tenant.name.substring(0, 2).toUpperCase()
                                            )}
                                            {tenant.status === 'SUSPENDED' && (
                                                <div className="absolute -top-1 -right-1 bg-amber-500 rounded-full p-1 border-2 border-white shadow-sm" title="Suspended">
                                                    <PauseCircle size={10} className="text-white" fill="currentColor" />
                                                </div>
                                            )}
                                        </div>
                                        <div>
                                            <h3 className="text-lg font-bold text-slate-800 flex items-center gap-2">
                                                {tenant.name}
                                                <span className={`text-[10px] px-2 py-0.5 rounded-full font-bold uppercase tracking-wide border ${getStatusColor(tenant.status)}`}>
                                                    {tenant.status}
                                                </span>
                                            </h3>
                                            <p className="text-xs text-slate-400 font-mono">ID: {tenant.id} • Created: {tenant.createdAt}</p>
                                        </div>
                                      </div>
                                      
                                      {/* Access Button */}
                                      <button 
                                          onClick={() => onImpersonate(tenant.id)}
                                          disabled={tenant.status !== 'ACTIVE'}
                                          className="flex items-center gap-2 px-4 py-2 bg-slate-900 text-white rounded-lg text-xs font-bold hover:bg-slate-800 shadow-sm transition-all disabled:opacity-50 disabled:cursor-not-allowed"
                                          title={tenant.status !== 'ACTIVE' ? `Cannot access ${tenant.status} tenant` : 'Access Dashboard'}
                                      >
                                          <LogIn size={14} /> Access Dashboard
                                      </button>
                                  </div>

                                  <div className="flex items-center gap-2 mt-5">
                                      <button 
                                        onClick={() => { setUserModalOpen({ isOpen: true, tenantId: tenant.id, tenantName: tenant.name }); setInviteLink(null); setAdminEmail(''); }}
                                        className="text-xs flex items-center gap-1.5 bg-white border border-slate-200 hover:border-indigo-300 text-slate-700 hover:text-indigo-600 px-3 py-1.5 rounded-md font-medium transition-colors shadow-sm"
                                      >
                                          <Users size={14} /> Manage Users
                                      </button>
                                      
                                      <div className="relative">
                                          <button 
                                              onClick={() => setActionMenuOpen(actionMenuOpen === tenant.id ? null : tenant.id)}
                                              className={`text-xs flex items-center gap-1.5 px-3 py-1.5 rounded-md font-medium transition-colors shadow-sm border ${actionMenuOpen === tenant.id ? 'bg-slate-100 border-slate-300 text-slate-900' : 'bg-white border-slate-200 hover:border-slate-300 text-slate-600'}`}
                                          >
                                              <Settings size={14} /> Actions
                                          </button>
                                          
                                          {actionMenuOpen === tenant.id && (
                                              <div className="absolute top-full left-0 mt-1 w-48 bg-white rounded-lg shadow-xl border border-slate-200 z-50 py-1 animate-in fade-in zoom-in-95 duration-100">
                                                  <button onClick={() => handleEditOpen(tenant)} className="w-full text-left px-4 py-2 text-xs font-medium text-slate-700 hover:bg-indigo-50 hover:text-indigo-700 flex items-center gap-2">
                                                      <LayoutTemplate size={14} /> Edit Branding
                                                  </button>
                                                  <div className="h-px bg-slate-100 my-1"></div>
                                                  {tenant.status !== 'ACTIVE' && (
                                                      <button onClick={() => handleStatusChange(tenant.id, 'ACTIVE')} className="w-full text-left px-4 py-2 text-xs font-medium text-slate-700 hover:bg-emerald-50 hover:text-emerald-700 flex items-center gap-2">
                                                          <PlayCircle size={14} /> Activate
                                                      </button>
                                                  )}
                                                  {tenant.status !== 'SUSPENDED' && (
                                                      <button onClick={() => handleStatusChange(tenant.id, 'SUSPENDED')} className="w-full text-left px-4 py-2 text-xs font-medium text-slate-700 hover:bg-amber-50 hover:text-amber-700 flex items-center gap-2">
                                                          <PauseCircle size={14} /> Suspend
                                                      </button>
                                                  )}
                                                  {tenant.status !== 'ARCHIVED' && (
                                                      <button onClick={() => handleStatusChange(tenant.id, 'ARCHIVED')} className="w-full text-left px-4 py-2 text-xs font-medium text-slate-700 hover:bg-slate-100 flex items-center gap-2">
                                                          <Archive size={14} /> Archive
                                                      </button>
                                                  )}
                                                  <div className="h-px bg-slate-100 my-1"></div>
                                                  <button onClick={() => handleDelete(tenant.id, tenant.name)} className="w-full text-left px-4 py-2 text-xs font-medium text-rose-600 hover:bg-rose-50 flex items-center gap-2">
                                                      <Trash2 size={14} /> Delete
                                                  </button>
                                              </div>
                                          )}
                                      </div>
                                  </div>
                              </div>

                              {/* Feature Toggles */}
                              <div className="xl:flex-[2] border-t xl:border-t-0 xl:border-l border-slate-100 pt-4 xl:pt-0 xl:pl-6">
                                  <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-4 flex items-center gap-2">
                                      Feature Configuration
                                      {tenant.status !== 'ACTIVE' && <span className="text-amber-500 text-[10px] normal-case font-normal border border-amber-200 bg-amber-50 px-1.5 rounded">(ReadOnly)</span>}
                                  </h4>
                                  <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
                                      {Object.entries(tenant.features).map(([key, isEnabled]) => (
                                          <div key={key} className={`flex items-center justify-between p-2 rounded-lg border border-slate-100 bg-slate-50/50 ${tenant.status !== 'ACTIVE' ? 'opacity-50 pointer-events-none' : ''}`}>
                                              <span className="text-xs text-slate-600 font-medium truncate pr-2" title={FEATURE_LABELS[key as keyof TenantFeatures]}>{FEATURE_LABELS[key as keyof TenantFeatures]}</span>
                                              <button 
                                                onClick={() => handleToggleFeature(tenant, key as keyof TenantFeatures)}
                                                disabled={tenant.status !== 'ACTIVE'}
                                                className={`relative inline-flex h-4 w-8 items-center rounded-full transition-colors focus:outline-none shrink-0 ${isEnabled ? 'bg-emerald-500' : 'bg-slate-300'}`}
                                              >
                                                  <span className={`inline-block h-2.5 w-2.5 transform rounded-full bg-white transition-transform ${isEnabled ? 'translate-x-4' : 'translate-x-0.5'}`} />
                                              </button>
                                          </div>
                                      ))}
                                  </div>
                              </div>
                          </div>
                          
                          {/* Footer */}
                          <div className="bg-slate-50 px-6 py-2 border-t border-slate-100 flex justify-between items-center text-xs text-slate-500 rounded-b-xl">
                              <span className="flex items-center gap-1"><Activity size={12} className={tenant.status === 'ACTIVE' ? "text-emerald-500" : "text-slate-400"} /> System {tenant.status === 'ACTIVE' ? 'Online' : 'Offline'}</span>
                              <span>Last synced: {tenant.status === 'ARCHIVED' ? 'Aug 24, 2023' : 'Just now'}</span>
                          </div>
                      </div>
                  ))}
              </div>
          </div>
      )}

      {/* CHIEF AUDITOR TAB */}
      {activeTab === 'chief_audit' && (
          <div className="animate-in fade-in slide-in-from-bottom-2 duration-300">
              <div className="bg-gradient-to-br from-slate-900 to-slate-800 rounded-xl p-8 border border-slate-700 shadow-xl mb-8 text-white relative overflow-hidden">
                  <div className="absolute top-0 right-0 w-96 h-96 bg-amber-500/10 rounded-full blur-3xl -mr-16 -mt-16 pointer-events-none"></div>
                  
                  <div className="relative z-10 flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
                      <div>
                          <h2 className="text-2xl font-bold flex items-center gap-3">
                              <Scale className="text-amber-400" size={32} />
                              Chief Financial Auditor
                          </h2>
                          <p className="text-slate-400 mt-2 max-w-xl text-sm leading-relaxed">
                              Expertise: 30 Years Experience • Big 4 Forensic Accounting • Federal Government Audit.
                              <br />
                              Role: Scrutinizes sub-agents and human overrides to ensure systemic integrity.
                          </p>
                      </div>
                      <button 
                          onClick={handleRunWeeklyAudit}
                          disabled={isRunningWeeklyAudit}
                          className="bg-amber-600 hover:bg-amber-500 text-white px-6 py-3 rounded-lg font-bold shadow-lg shadow-amber-900/50 transition-all flex items-center gap-2 disabled:opacity-50"
                      >
                          {isRunningWeeklyAudit ? <Loader2 className="animate-spin" /> : <ScrollText />}
                          Run Weekly Integrity Audit
                      </button>
                  </div>
              </div>

              {weeklyReport && (
                  <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden animate-in fade-in slide-in-from-bottom-4">
                      <div className="bg-slate-50 px-6 py-4 border-b border-slate-200 flex justify-between items-center">
                          <h3 className="font-bold text-slate-800">Audit Report: {weeklyReport.period}</h3>
                          <span className={`px-3 py-1 rounded-full text-xs font-bold border ${weeklyReport.systemHealthScore > 80 ? 'bg-emerald-100 text-emerald-800 border-emerald-200' : 'bg-amber-100 text-amber-800 border-amber-200'}`}>
                              System Health: {weeklyReport.systemHealthScore}/100
                          </span>
                      </div>
                      <div className="p-8 grid grid-cols-1 md:grid-cols-2 gap-8">
                          <div>
                              <h4 className="text-sm font-bold text-slate-500 uppercase tracking-wider mb-3">Agent Performance</h4>
                              <div className="bg-slate-50 p-4 rounded-lg border border-slate-200 space-y-2">
                                  <div className="flex justify-between text-sm">
                                      <span className="text-slate-600">Accuracy Rating</span>
                                      <span className="font-bold text-slate-800">{weeklyReport.agentPerformance.accuracy}%</span>
                                  </div>
                                  <div className="flex justify-between text-sm">
                                      <span className="text-slate-600">False Positives</span>
                                      <span className="font-bold text-slate-800">{weeklyReport.agentPerformance.falsePositives}</span>
                                  </div>
                                  <p className="text-xs text-slate-500 mt-2 pt-2 border-t border-slate-200 italic">
                                      "{weeklyReport.agentPerformance.summary}"
                                  </p>
                              </div>
                          </div>

                          <div>
                              <h4 className="text-sm font-bold text-slate-500 uppercase tracking-wider mb-3">Identified Fraud Trends</h4>
                              <ul className="space-y-2">
                                  {weeklyReport.fraudTrends.map((trend, i) => (
                                      <li key={i} className="flex items-start gap-2 text-sm text-rose-700 bg-rose-50 p-2 rounded border border-rose-100">
                                          <AlertTriangle size={16} className="shrink-0 mt-0.5" />
                                          {trend}
                                      </li>
                                  ))}
                              </ul>
                          </div>

                          <div className="md:col-span-2">
                              <h4 className="text-sm font-bold text-slate-500 uppercase tracking-wider mb-3">Human Oversight Analysis</h4>
                              <p className="text-sm text-slate-700 bg-blue-50 p-4 rounded-lg border border-blue-100 leading-relaxed">
                                  {weeklyReport.humanOversightAnalysis}
                              </p>
                          </div>

                          <div className="md:col-span-2">
                              <h4 className="text-sm font-bold text-slate-500 uppercase tracking-wider mb-3">Critical Recommendations</h4>
                              <div className="grid gap-3">
                                  {weeklyReport.criticalRecommendations.map((rec, i) => (
                                      <div key={i} className="flex items-center gap-3 bg-white p-3 rounded border border-slate-200 shadow-sm">
                                          <span className="w-6 h-6 rounded-full bg-slate-900 text-white flex items-center justify-center text-xs font-bold shrink-0">{i + 1}</span>
                                          <span className="text-sm text-slate-800">{rec}</span>
                                      </div>
                                  ))}
                              </div>
                          </div>
                      </div>
                  </div>
              )}
          </div>
      )}

      {/* SYSTEM HEALTH TAB */}
      {activeTab === 'system' && (
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 animate-in fade-in slide-in-from-bottom-2 duration-300">
              {/* System Logs */}
              <div className="bg-slate-900 rounded-xl border border-slate-800 p-6 font-mono text-sm text-slate-300 h-96 overflow-y-auto">
                  <h3 className="text-white font-bold mb-4 flex items-center gap-2"><Terminal size={18} /> System Live Logs</h3>
                  <div className="space-y-2">
                      <p><span className="text-emerald-400">[INFO]</span> Service 'Orchestrator' connected on port 8080</p>
                      <p><span className="text-emerald-400">[INFO]</span> Tenant 't-001' PO Sync completed (14 records)</p>
                      <p><span className="text-amber-400">[WARN]</span> Tenant 't-003' Xero API Rate Limit approaching</p>
                      <p><span className="text-emerald-400">[INFO]</span> New Invoice 'INV-992' ingested for Tenant 't-001'</p>
                      <p><span className="text-blue-400">[DEBUG]</span> Gemini API latency: 450ms</p>
                      <p><span className="text-emerald-400">[INFO]</span> Backup routine started...</p>
                      <p><span className="text-emerald-400">[INFO]</span> Backup routine completed (Size: 45MB)</p>
                      <p className="animate-pulse">_</p>
                  </div>
              </div>

              {/* Server Stats */}
              <div className="space-y-6">
                  <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm">
                      <h3 className="font-bold text-slate-800 mb-4 flex items-center gap-2"><Server size={18} className="text-blue-500" /> Infrastructure</h3>
                      <div className="space-y-4">
                          <div>
                              <div className="flex justify-between text-xs mb-1 font-medium text-slate-600">
                                  <span>CPU Usage (US-East)</span>
                                  <span>24%</span>
                              </div>
                              <div className="w-full bg-slate-100 rounded-full h-2"><div className="bg-blue-500 h-2 rounded-full" style={{width: '24%'}}></div></div>
                          </div>
                          <div>
                              <div className="flex justify-between text-xs mb-1 font-medium text-slate-600">
                                  <span>Memory (Workers)</span>
                                  <span>62%</span>
                              </div>
                              <div className="w-full bg-slate-100 rounded-full h-2"><div className="bg-indigo-500 h-2 rounded-full" style={{width: '62%'}}></div></div>
                          </div>
                      </div>
                  </div>

                  <div className="bg-white p-6 rounded-xl border border-slate-200 shadow-sm">
                      <h3 className="font-bold text-slate-800 mb-4 flex items-center gap-2"><Database size={18} className="text-emerald-500" /> Database Metrics</h3>
                      <div className="grid grid-cols-2 gap-4">
                          <div className="p-3 bg-slate-50 rounded-lg text-center">
                              <p className="text-xs text-slate-500">Total Records</p>
                              <p className="text-xl font-bold text-slate-800">1.2M</p>
                          </div>
                          <div className="p-3 bg-slate-50 rounded-lg text-center">
                              <p className="text-xs text-slate-500">Read Latency</p>
                              <p className="text-xl font-bold text-emerald-600">12ms</p>
                          </div>
                      </div>
                  </div>
              </div>
          </div>
      )}

      {/* GLOBAL SETTINGS TAB */}
      {activeTab === 'global_config' && (
          <div className="animate-in fade-in slide-in-from-bottom-2 duration-300 max-w-2xl">
              <div className="bg-white rounded-xl shadow-sm border border-slate-200 p-6 space-y-6">
                  <div>
                      <h3 className="text-lg font-bold text-slate-800 mb-1">Global System Configuration</h3>
                      <p className="text-sm text-slate-500">Settings here affect ALL tenants and users immediately.</p>
                  </div>

                  <div className="space-y-4">
                      {/* Maintenance Mode */}
                      <div className="flex items-center justify-between p-4 rounded-lg bg-slate-50 border border-slate-200">
                          <div>
                              <div className="flex items-center gap-2">
                                  <AlertTriangle size={18} className="text-amber-500" />
                                  <span className="font-bold text-slate-700">Maintenance Mode</span>
                              </div>
                              <p className="text-xs text-slate-500 mt-1 max-w-md">
                                  If enabled, all non-superuser access will be blocked with a "Under Maintenance" page.
                              </p>
                          </div>
                          <button 
                              onClick={() => setGlobalConfig(prev => ({ ...prev, maintenanceMode: !prev.maintenanceMode }))}
                              className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors focus:outline-none ${globalConfig.maintenanceMode ? 'bg-amber-500' : 'bg-slate-300'}`}
                          >
                              <span className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${globalConfig.maintenanceMode ? 'translate-x-6' : 'translate-x-1'}`} />
                          </button>
                      </div>

                      {/* System Banner */}
                      <div className="p-4 rounded-lg bg-white border border-slate-200">
                          <label className="block text-sm font-bold text-slate-700 mb-2 flex items-center gap-2">
                              <Bell size={16} className="text-blue-500" /> System-wide Announcement
                          </label>
                          <input 
                              type="text" 
                              value={globalConfig.systemBanner} 
                              onChange={(e) => setGlobalConfig(prev => ({ ...prev, systemBanner: e.target.value }))}
                              className="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm bg-white text-black focus:bg-white transition-colors outline-none focus:ring-2 focus:ring-blue-500"
                              placeholder="e.g. Scheduled downtime this Sunday at 2am UTC"
                          />
                          <p className="text-xs text-slate-400 mt-2">Will appear as a dismissal banner at the top of all tenant dashboards.</p>
                      </div>

                      {/* Region */}
                      <div className="p-4 rounded-lg bg-white border border-slate-200">
                          <label className="block text-sm font-bold text-slate-700 mb-2 flex items-center gap-2">
                              <Globe size={16} className="text-emerald-500" /> Default Data Region
                          </label>
                          <select 
                              value={globalConfig.defaultRegion}
                              onChange={(e) => setGlobalConfig(prev => ({ ...prev, defaultRegion: e.target.value }))}
                              className="w-full px-3 py-2 border border-slate-300 rounded-lg text-sm bg-white text-black outline-none focus:ring-2 focus:ring-blue-500"
                          >
                              <option value="au-southeast-1">Australia (Sydney) - Recommended</option>
                              <option value="us-east-1">United States (N. Virginia)</option>
                              <option value="eu-west-1">Europe (Ireland)</option>
                          </select>
                          <p className="text-xs text-slate-400 mt-2">New tenants will default to this region for data residency.</p>
                      </div>
                  </div>

                  <div className="pt-4 border-t border-slate-100 flex justify-end">
                      <button 
                          onClick={() => alert("Global configuration saved successfully.")}
                          className="bg-slate-900 text-white px-6 py-2.5 rounded-lg font-bold hover:bg-slate-800 transition-colors shadow-lg shadow-slate-200"
                      >
                          Save Changes
                      </button>
                  </div>
              </div>
          </div>
      )}

      {/* CREATE TENANT MODAL */}
      {isCreateModalOpen && (
          <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4">
              <div className="bg-white rounded-2xl shadow-2xl w-full max-w-lg animate-in fade-in zoom-in duration-200 max-h-[90vh] overflow-y-auto">
                  <div className="p-6 border-b border-slate-100 flex justify-between items-center sticky top-0 bg-white z-10">
                      <h3 className="text-lg font-bold text-slate-800">New Organisation</h3>
                      <button onClick={() => setIsCreateModalOpen(false)}><X size={20} className="text-slate-400" /></button>
                  </div>
                  <form onSubmit={handleCreateTenant} className="p-6 space-y-6">
                      <div>
                          <label className="block text-sm font-medium text-slate-700 mb-1">Organisation Name</label>
                          <input 
                              type="text" 
                              required 
                              value={newOrgName}
                              onChange={(e) => setNewOrgName(e.target.value)}
                              className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-indigo-500 outline-none bg-white text-black" 
                              placeholder="e.g. Acme Care Services"
                          />
                      </div>
                      
                      {/* White Labeling Section */}
                      <div className="space-y-4">
                          <h4 className="text-xs font-bold text-slate-500 uppercase tracking-wider flex items-center gap-2">
                              <Palette size={14} /> White Labeling Setup
                          </h4>

                          {/* AI Generator in Create Modal */}
                          <div className="bg-indigo-50 border border-indigo-100 p-4 rounded-lg">
                              <div className="flex justify-between items-center mb-2">
                                  <h5 className="text-xs font-bold text-indigo-800 flex items-center gap-1"><Sparkles size={12} /> AI Auto-Brand</h5>
                              </div>
                              <div className="grid grid-cols-2 gap-3">
                                  <input 
                                      type="text" 
                                      value={newOrgWebsite}
                                      onChange={(e) => setNewOrgWebsite(e.target.value)}
                                      placeholder="https://company.com"
                                      className="px-3 py-1.5 text-xs border border-indigo-200 rounded focus:outline-none focus:border-indigo-400 bg-white text-black"
                                  />
                                  <button 
                                      type="button"
                                      onClick={() => handleGenerateBranding('create', newOrgWebsite, newOrgLogo)}
                                      disabled={isGeneratingCreate}
                                      className="bg-indigo-600 text-white text-xs font-bold px-3 py-1.5 rounded hover:bg-indigo-700 flex items-center justify-center gap-1 disabled:opacity-70"
                                  >
                                      {isGeneratingCreate ? <Loader2 size={12} className="animate-spin" /> : 'Auto-Generate'}
                                  </button>
                              </div>
                          </div>
                          
                          <div>
                              <label className="block text-sm font-medium text-slate-700 mb-1">Brand Color (Primary)</label>
                              <div className="flex items-center gap-3">
                                  <input 
                                      type="color" 
                                      value={newOrgColor}
                                      onChange={(e) => setNewOrgColor(e.target.value)}
                                      className="h-10 w-10 p-0 rounded border-0 cursor-pointer"
                                  />
                                  <span className="text-sm font-mono text-slate-500">{newOrgColor}</span>
                              </div>
                          </div>

                          <div>
                              <label className="block text-sm font-medium text-slate-700 mb-1">Logo URL (Optional)</label>
                              <div className="flex items-center gap-2">
                                  <button 
                                      type="button"
                                      onClick={() => createLogoRef.current?.click()}
                                      className="p-2 bg-slate-100 rounded hover:bg-slate-200 text-slate-600"
                                  >
                                      <ImageIcon size={18} />
                                  </button>
                                  <input 
                                      type="text" 
                                      value={newOrgLogo}
                                      onChange={(e) => setNewOrgLogo(e.target.value)}
                                      className="flex-1 px-3 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-indigo-500 outline-none text-sm bg-white text-black"
                                      placeholder="https://example.com/logo.png"
                                  />
                                  <input 
                                      type="file" 
                                      ref={createLogoRef} 
                                      className="hidden" 
                                      accept="image/*"
                                      onChange={(e) => handleFileUpload(e, 'create')} 
                                  />
                              </div>
                          </div>
                          
                          {/* Document Settings Fields */}
                          <div className="border-t border-slate-100 pt-4 mt-2">
                               <h5 className="text-xs font-bold text-slate-500 uppercase mb-2 flex items-center gap-2">
                                  <LayoutTemplate size={12} /> Document Defaults
                               </h5>
                               <div className="grid grid-cols-2 gap-3">
                                   <div>
                                       <label className="block text-xs font-medium text-slate-600 mb-1">Header</label>
                                       <input 
                                          type="text" 
                                          className="w-full border border-slate-300 bg-white text-black p-1.5 rounded text-xs" 
                                          placeholder="Org Name"
                                          value={newOrgDocSettings.headerText}
                                          onChange={e => setNewOrgDocSettings(p => ({ ...p, headerText: e.target.value }))}
                                       />
                                   </div>
                                   <div>
                                       <label className="block text-xs font-medium text-slate-600 mb-1">Footer</label>
                                       <input 
                                          type="text" 
                                          className="w-full border border-slate-300 bg-white text-black p-1.5 rounded text-xs" 
                                          placeholder="Confidential..."
                                          value={newOrgDocSettings.footerText}
                                          onChange={e => setNewOrgDocSettings(p => ({ ...p, footerText: e.target.value }))}
                                       />
                                   </div>
                               </div>
                          </div>

                          <BrandingPreview name={newOrgName} color={newOrgColor} logoUrl={newOrgLogo} />
                      </div>

                      <div className="pt-2">
                          <button type="submit" className="w-full py-2.5 bg-indigo-600 text-white rounded-lg font-bold hover:bg-indigo-700 transition-colors shadow-sm">Create Organisation</button>
                      </div>
                  </form>
              </div>
          </div>
      )}

      {/* EDIT TENANT BRANDING MODAL */}
      {editingTenant && (
          <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4">
              <div className="bg-white rounded-2xl shadow-2xl w-full max-w-lg animate-in fade-in zoom-in duration-200 max-h-[90vh] overflow-y-auto">
                  <div className="p-6 border-b border-slate-100 flex justify-between items-center sticky top-0 bg-white z-10">
                      <div>
                          <h3 className="text-lg font-bold text-slate-800">Edit Organisation & Branding</h3>
                          <p className="text-xs text-slate-500">ID: {editingTenant.id}</p>
                      </div>
                      <button onClick={() => setEditingTenant(null)}><X size={20} className="text-slate-400" /></button>
                  </div>
                  <form onSubmit={handleUpdateTenant} className="p-6 space-y-6">
                      <div>
                          <label className="block text-sm font-medium text-slate-700 mb-1">Organisation Name</label>
                          <input 
                              type="text" 
                              required 
                              value={editForm.name}
                              onChange={(e) => setEditForm({...editForm, name: e.target.value})}
                              className="w-full px-3 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-indigo-500 outline-none bg-white text-black" 
                          />
                      </div>
                      
                      {/* White Labeling Section */}
                      <div className="space-y-4">
                          <h4 className="text-xs font-bold text-slate-500 uppercase tracking-wider flex items-center gap-2">
                              <Palette size={14} /> Branding Configuration
                          </h4>

                          {/* AI Generator in Edit Modal */}
                          <div className="bg-indigo-50 border border-indigo-100 p-4 rounded-lg">
                              <div className="flex justify-between items-center mb-2">
                                  <h5 className="text-xs font-bold text-indigo-800 flex items-center gap-1"><Sparkles size={12} /> AI Auto-Brand</h5>
                              </div>
                              <div className="grid grid-cols-2 gap-3">
                                  <input 
                                      type="text" 
                                      value={editForm.website}
                                      onChange={(e) => setEditForm({...editForm, website: e.target.value})}
                                      placeholder="https://company.com"
                                      className="px-3 py-1.5 text-xs border border-indigo-200 rounded focus:outline-none focus:border-indigo-400 bg-white text-black"
                                  />
                                  <button 
                                      type="button"
                                      onClick={() => handleGenerateBranding('edit', editForm.website, editForm.logoUrl)}
                                      disabled={isGeneratingEdit}
                                      className="bg-indigo-600 text-white text-xs font-bold px-3 py-1.5 rounded hover:bg-indigo-700 flex items-center justify-center gap-1 disabled:opacity-70"
                                  >
                                      {isGeneratingEdit ? <Loader2 size={12} className="animate-spin" /> : 'Auto-Generate'}
                                  </button>
                              </div>
                          </div>
                          
                          <div>
                              <label className="block text-sm font-medium text-slate-700 mb-1">Brand Color (Primary)</label>
                              <div className="flex items-center gap-3">
                                  <input 
                                      type="color" 
                                      value={editForm.primaryColor}
                                      onChange={(e) => setEditForm({...editForm, primaryColor: e.target.value})}
                                      className="h-10 w-10 p-0 rounded border-0 cursor-pointer"
                                  />
                                  <span className="text-sm font-mono text-slate-500">{editForm.primaryColor}</span>
                              </div>
                          </div>

                          <div>
                              <label className="block text-sm font-medium text-slate-700 mb-1">Logo URL</label>
                              <div className="flex items-center gap-2">
                                  <button 
                                      type="button"
                                      onClick={() => editLogoRef.current?.click()}
                                      className="p-2 bg-slate-100 rounded hover:bg-slate-200 text-slate-600"
                                  >
                                      <ImageIcon size={18} />
                                  </button>
                                  <input 
                                      type="text" 
                                      value={editForm.logoUrl}
                                      onChange={(e) => setEditForm({...editForm, logoUrl: e.target.value})}
                                      className="flex-1 px-3 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-indigo-500 outline-none text-sm bg-white text-black"
                                      placeholder="https://example.com/logo.png"
                                  />
                                  <input 
                                      type="file" 
                                      ref={editLogoRef} 
                                      className="hidden" 
                                      accept="image/*"
                                      onChange={(e) => handleFileUpload(e, 'edit')} 
                                  />
                              </div>
                          </div>

                          {/* Document Settings Fields */}
                          <div className="border-t border-slate-100 pt-4 mt-2">
                               <h5 className="text-xs font-bold text-slate-500 uppercase mb-2 flex items-center gap-2">
                                  <LayoutTemplate size={12} /> Document Defaults
                               </h5>
                               <div className="space-y-2">
                                   <div>
                                       <label className="block text-xs font-medium text-slate-600 mb-1">Header Text</label>
                                       <input 
                                          type="text" 
                                          className="w-full border border-slate-300 bg-white text-black p-1.5 rounded text-xs" 
                                          placeholder="Org Name"
                                          value={editForm.documentSettings(editingTenant).headerText}
                                          onChange={e => setEditForm(p => ({ ...p, documentSettings: () => ({ ...p.documentSettings(editingTenant), headerText: e.target.value }) }))}
                                       />
                                   </div>
                                    <div>
                                       <label className="block text-xs font-medium text-slate-600 mb-1">Sub-Header</label>
                                       <input 
                                          type="text" 
                                          className="w-full border border-slate-300 bg-white text-black p-1.5 rounded text-xs" 
                                          placeholder="Slogan"
                                          value={editForm.documentSettings(editingTenant).subHeaderText}
                                          onChange={e => setEditForm(p => ({ ...p, documentSettings: () => ({ ...p.documentSettings(editingTenant), subHeaderText: e.target.value }) }))}
                                       />
                                   </div>
                                   <div>
                                       <label className="block text-xs font-medium text-slate-600 mb-1">Footer Text</label>
                                       <input 
                                          type="text" 
                                          className="w-full border border-slate-300 bg-white text-black p-1.5 rounded text-xs" 
                                          placeholder="Confidential..."
                                          value={editForm.documentSettings(editingTenant).footerText}
                                          onChange={e => setEditForm(p => ({ ...p, documentSettings: () => ({ ...p.documentSettings(editingTenant), footerText: e.target.value }) }))}
                                       />
                                   </div>
                                   <div className="flex items-center gap-2">
                                        <input 
                                            type="checkbox" 
                                            id="editShowLogo"
                                            checked={editForm.documentSettings(editingTenant).showLogo}
                                            onChange={e => setEditForm(p => ({ ...p, documentSettings: () => ({ ...p.documentSettings(editingTenant), showLogo: e.target.checked }) }))}
                                            className="rounded text-indigo-600"
                                        />
                                        <label htmlFor="editShowLogo" className="text-xs text-slate-700">Include Logo in Header</label>
                                   </div>
                               </div>
                          </div>

                          <BrandingPreview name={editForm.name} color={editForm.primaryColor} logoUrl={editForm.logoUrl} />
                      </div>

                      <div className="pt-2 flex justify-end gap-3">
                          <button type="button" onClick={() => setEditingTenant(null)} className="px-4 py-2 text-slate-600 hover:bg-slate-100 rounded-lg font-medium">Cancel</button>
                          <button type="submit" className="px-6 py-2 bg-indigo-600 text-white rounded-lg font-bold hover:bg-indigo-700 transition-colors shadow-sm">Save Changes</button>
                      </div>
                  </form>
              </div>
          </div>
      )}

      {/* MANAGE USERS MODAL */}
      {userModalOpen.isOpen && (
          <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4">
              <div className="bg-white rounded-2xl shadow-2xl w-full max-w-lg animate-in fade-in zoom-in duration-200">
                  <div className="p-6 border-b border-slate-100 flex justify-between items-center">
                      <div>
                          <h3 className="text-lg font-bold text-slate-800">Manage Users</h3>
                          <p className="text-xs text-slate-500">{userModalOpen.tenantName}</p>
                      </div>
                      <button onClick={() => setUserModalOpen({ ...userModalOpen, isOpen: false })}><X size={20} className="text-slate-400" /></button>
                  </div>
                  <div className="p-6">
                      
                      {/* Invite Section */}
                      <div className="mb-8 p-4 bg-slate-50 rounded-xl border border-slate-200">
                          <label className="block text-xs font-bold text-slate-700 uppercase mb-2">Invite New User</label>
                          {!inviteLink ? (
                              <div className="space-y-3">
                                  <div className="flex gap-2">
                                      <input 
                                          type="email" 
                                          value={adminEmail}
                                          onChange={(e) => setAdminEmail(e.target.value)}
                                          className="flex-1 px-3 py-2 border border-slate-300 rounded-lg focus:ring-2 focus:ring-indigo-500 outline-none text-sm bg-white text-black"
                                          placeholder="user@company.com"
                                      />
                                      <select 
                                          value={adminRole}
                                          onChange={(e) => setAdminRole(e.target.value)}
                                          className="px-3 py-2 border border-slate-300 rounded-lg text-sm bg-white text-black focus:ring-2 focus:ring-indigo-500 outline-none"
                                      >
                                          <option value="Administrator">Admin</option>
                                          <option value="Officer">Officer</option>
                                          <option value="Viewer">Viewer</option>
                                      </select>
                                  </div>
                                  <button 
                                      onClick={generateInvite}
                                      disabled={!adminEmail}
                                      className="w-full bg-indigo-600 text-white px-4 py-2 rounded-lg font-bold hover:bg-indigo-700 transition-colors disabled:opacity-50 text-sm"
                                  >
                                      Generate Invite Link
                                  </button>
                              </div>
                          ) : (
                             <div className="bg-emerald-50 border border-emerald-100 rounded-lg p-3 flex items-center justify-between gap-2">
                                 <div className="text-xs text-emerald-700 truncate flex-1 font-mono">{inviteLink}</div>
                                 <button onClick={copyToClipboard} className="text-emerald-600 hover:text-emerald-800 p-1">
                                     {copied ? <Check size={16} /> : <Copy size={16} />}
                                 </button>
                             </div>
                          )}
                      </div>

                      {/* User List */}
                      <div>
                          <label className="block text-xs font-bold text-slate-700 uppercase mb-3">Active Users</label>
                          <div className="border border-slate-200 rounded-xl overflow-hidden max-h-60 overflow-y-auto">
                              {currentTenantUsers.length > 0 ? currentTenantUsers.map((user, idx) => (
                                  <div key={user.id} className={`p-3 flex items-center justify-between ${idx !== currentTenantUsers.length - 1 ? 'border-b border-slate-100' : ''} hover:bg-slate-50 transition-colors`}>
                                      <div className="flex items-center gap-3">
                                          <div className={`w-8 h-8 rounded-full flex items-center justify-center text-xs font-bold ${user.role === 'Administrator' ? 'bg-purple-100 text-purple-700' : 'bg-slate-100 text-slate-600'}`}>
                                              {user.email[0].toUpperCase()}
                                          </div>
                                          <div>
                                              <p className="text-sm font-medium text-slate-800">{user.email}</p>
                                              <div className="flex gap-2 text-[10px] text-slate-500">
                                                  <span className="font-semibold">{user.role}</span>
                                                  <span>•</span>
                                                  <span>{user.status}</span>
                                              </div>
                                          </div>
                                      </div>
                                      <div className="relative group">
                                           <button className="p-2 text-slate-400 hover:text-slate-600"><MoreVertical size={16} /></button>
                                           <div className="absolute right-0 top-8 bg-white shadow-xl border border-slate-100 rounded-lg w-32 hidden group-hover:block z-10 p-1">
                                               <button onClick={() => handleResetPassword(user.email)} className="w-full text-left px-3 py-1.5 text-xs text-slate-600 hover:bg-slate-50 rounded flex items-center gap-2">
                                                   <RefreshCw size={12} /> Reset Pwd
                                               </button>
                                               <button onClick={() => handleRevokeUser(user.id)} className="w-full text-left px-3 py-1.5 text-xs text-rose-600 hover:bg-rose-50 rounded flex items-center gap-2">
                                                   <X size={12} /> Revoke
                                               </button>
                                           </div>
                                      </div>
                                  </div>
                              )) : (
                                <div className="p-6 text-center text-slate-400 text-sm italic">No active users found.</div>
                              )}
                          </div>
                      </div>

                  </div>
              </div>
          </div>
      )}
    </div>
  );
};

export default SuperuserDashboard;
